# Generated by Django 5.1.8 on 2025-10-18 15:25

import rockflint_web.users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_profile_phone_number_vendor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, validators=[rockflint_web.users.models.validate_phone_number]),
        ),
    ]
