# Generated by Django 5.1.8 on 2026-01-26 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_alter_profile_names_password_reset_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="email_verification_expiry",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
