# Generated by Django 5.1.8 on 2025-10-18 14:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0004_alter_profile_phone_number_vendor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('icon', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LGA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['state__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=512, null=True)),
                ('price', models.DecimalField(db_index=True, decimal_places=2, max_digits=14)),
                ('rent_period', models.CharField(blank=True, max_length=20, null=True)),
                ('bedrooms', models.PositiveSmallIntegerField(blank=True, db_index=True, null=True)),
                ('bathrooms', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('area', models.FloatField(blank=True, help_text='Area in sqft/meters', null=True)),
                ('building_age_years', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('attributes', models.JSONField(blank=True, default=dict)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='listings', to='ads.category')),
                ('features', models.ManyToManyField(blank=True, related_name='listings', to='ads.feature')),
                ('lga', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='listings', to='ads.lga')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='users.vendor')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='listings', to='ads.offer')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='listings', to='ads.state')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='ListingImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='listings/')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('is_primary', models.BooleanField(db_index=True, default=False)),
                ('order', models.PositiveSmallIntegerField(db_index=True, default=0)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='ads.listing')),
            ],
            options={
                'ordering': ['order', '-is_primary', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PromotedListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promoted_until', models.DateTimeField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('listing', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='promotion', to='ads.listing')),
            ],
        ),
        migrations.AddField(
            model_name='lga',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lgas', to='ads.state'),
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='ads.listing')),
            ],
            options={
                'ordering': ['-saved_at'],
                'unique_together': {('user', 'listing')},
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('comment', models.TextField()),
                ('rating', models.PositiveSmallIntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='ads.listing')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
                'unique_together': {('user', 'listing')},
            },
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['slug'], name='ads_listing_slug_c20fd8_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['category', 'state', 'lga'], name='ads_listing_categor_ec9c7f_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['price'], name='ads_listing_price_37e535_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['active'], name='ads_listing_active_7f2708_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='lga',
            unique_together={('state', 'name')},
        ),
    ]
